touch ft_memset.c
touch ft_bzero.c
touch ft_memcpy.c
touch ft_memccpy.c
touch ft_memmove.c
touch ft_memchr.c
touch ft_memcmp.c
touch ft_strlen.c
touch ft_isalpha.c
touch ft_isdigit.c
touch ft_isalnum.c
touch ft_isascii.c
touch ft_isprint.c
touch ft_toupper.c
touch ft_tolower.c
touch ft_strchr.c
touch ft_strrchr.c
touch ft_strncmp.c
touch ft_strlcpy.c
touch ft_strlcat.c
touch ft_strnstr.c
touch ft_atoi.c
touch ft_calloc.c
touch ft_strdup.c
